# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleAppWithComponents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleAppWithComponents
  pod 'Validator'
  pod 'TTTAttributedLabel', '2.0.0'
  pod 'DLRadioButton', '1.4.12'
  pod 'NVActivityIndicatorView'
  pod 'SwiftHEXColors'

end
