//
//  LoginModels.swift
//  SampleAppWithComponents
//
//  Created by Rahul Mane on 20/09/19.
//  Copyright (c) 2019 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Validator


enum Login{
    enum UIComponents{
        case icon //for icon
        case email // for email textfield
        case password // for password textfield
        case forgotpassword // for forgot password textfield
        case signInbutton // for sign in button
        case signInOption // for sign in option label
        case signUpOption // for sign up option label
    }
    
    
    enum UI{
        struct Request{}
        struct Response{
            var uiComponenets : [UIComponents]?
        }
        
        struct ViewModel{
            var cellConfigs : [(Login.UIComponents, BaseCellConfig)]?
        }
    }
    
    enum Validate{
        struct Request {
            var email : String?
            var password : String?
        }
        
        struct Response{
            var validationResultEmail : ValidationResult?
            var validationResultPassword : ValidationResult?
        }
        
        struct ViewModel{
            var errorMessageForEmail : NSAttributedString?
            var errorMessageForPassword : NSAttributedString?
        }
    }
    
    enum SignIn{
        struct Request{}
        struct Response{}
        struct ViewModel{}
        struct ErrorViewModel{
            var error : NSAttributedString?
        }
    }
    
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
