//
//  CreateProfileModels.swift
//  SampleAppWithComponents
//
//  Created by Rahul Mane on 16/10/19.
//  Copyright (c) 2019 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateProfile{
    
    enum UIComponents{
        case infoOfScreen
        case firstName
        case lastName
        case phoneNumber
        case address
        case submit
    }
    
    enum UI{
        struct Request{}
        struct Response{
            var uiComponenets : [UIComponents]?
        }
        
        struct ViewModel{
            var cellConfigs : [(CreateProfile.UIComponents, BaseCellConfig)]?
        }
    }
    
    // MARK: Use cases
    enum Something
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
