//
//  CreateProfileInteractor.swift
//  SampleAppWithComponents
//
//  Created by Rahul Mane on 16/10/19.
//  Copyright (c) 2019 developer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateProfileBusinessLogic{
    func doSomething(request: CreateProfile.Something.Request)
    func requiredUIForScreen(request: CreateProfile.UI.Request)
}

protocol CreateProfileDataStore
{
    //var name: String { get set }
}

class CreateProfileInteractor: CreateProfileBusinessLogic, CreateProfileDataStore
{
    var presenter: CreateProfilePresentationLogic?
    var worker: CreateProfileWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CreateProfile.Something.Request)
    {
        worker = CreateProfileWorker()
        worker?.doSomeWork()
        
        let response = CreateProfile.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func requiredUIForScreen(request: CreateProfile.UI.Request){
        let uiComponenets = [CreateProfile.UIComponents.infoOfScreen,
                             CreateProfile.UIComponents.firstName,
                             CreateProfile.UIComponents.lastName,
                             CreateProfile.UIComponents.phoneNumber,
                             CreateProfile.UIComponents.address,
                             CreateProfile.UIComponents.submit]
        
        let response = CreateProfile.UI.Response(uiComponenets: uiComponenets)
        presenter?.presentUI(response: response)
    }
    

}
